Improve Readme.md file
evaldez89/banks-transaction-email-reader pull request #1
Opened 2019-12-31 22:37 UTC by RicardoBritoBrens

Fix some typo and just make it more readable.

2019-12-31 23:10 UTC, evaldez89 commented
@RicardoBritoBrens pull recent changes from master.

2020-01-02 16:22 UTC, evaldez89 requested changes
Actually we wouln't want to predefined the banks the app will work with, we want to go further than our reach. In example, a person from another contry could add a bank we don't know of. That being said:

- [x] Just highligth available banks and banks in progress

2020-01-02 16:22 UTC, evaldez89 commented on README.md
> +### Bancos Extranjeros
@RicardoBritoBrens FYI

2020-01-05 17:15 UTC, evaldez89 commented
@RicardoBritoBrens :robot:

2020-01-12 21:58 UTC, RicardoBritoBrens commented
Changes done.

2020-01-12 22:31 UTC, evaldez89 approved these changes

2020-01-12 22:31 UTC, evaldez89 commented on README.md
> +     1. Currently only Gmail is supported. Stay tunned for instructions on how to add a new service.
don use specific sequence just `1. ` that way it renders automatically

1. blah
1. blah
   1. sub blah

2020-01-12 22:31 UTC, evaldez89 commented on README.md
> -## The current supported email services are:
This section is missing

2020-01-12 22:32 UTC, merged